### ISSUE TITLE
Icons missing when trying to add block in the storybook

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-storybook#1]
![Screenshot 2021-01-13 at 12 58 24](https://user-images.githubusercontent.com/8638515/104449568-15de8e00-559f-11eb-8d34-b04b68b2689a.png)

https://infinum.github.io/eightshift-docs/storybook/

**Comment by iruzevic** [comment]
This is because they moved Dashicon, I have to test this

**Comment by iruzevic** [comment]
this is fixed
